Traceback (most recent call last):
  File "/home/narisam/sp23-nmep-hw1/main.py", line 301, in <module>
    main(config)
  File "/home/narisam/sp23-nmep-hw1/main.py", line 116, in main
    train_acc1, train_loss = train_one_epoch(config, model, criterion, data_loader_train, optimizer, epoch)
  File "/home/narisam/sp23-nmep-hw1/main.py", line 163, in train_one_epoch
    for idx, (samples, targets) in enumerate(tqdm(data_loader, leave=False)):
  File "/home/narisam/miniconda3/lib/python3.10/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/home/narisam/miniconda3/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/home/narisam/miniconda3/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1333, in _next_data
    return self._process_data(data)
  File "/home/narisam/miniconda3/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1359, in _process_data
    data.reraise()
  File "/home/narisam/miniconda3/lib/python3.10/site-packages/torch/_utils.py", line 543, in reraise
    raise exception
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/narisam/miniconda3/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/narisam/miniconda3/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/narisam/miniconda3/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/narisam/sp23-nmep-hw1/data/datasets.py", line 109, in __getitem__
    image = self.transform(image)
  File "/home/narisam/miniconda3/lib/python3.10/site-packages/torchvision/transforms/transforms.py", line 95, in __call__
    img = t(img)
  File "/home/narisam/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/narisam/miniconda3/lib/python3.10/site-packages/torchvision/transforms/transforms.py", line 1991, in forward
    if torch.rand(1).item() < self.p:
TypeError: '<' not supported between instances of 'float' and 'list'